sonar.projectKey=FutList
sonar.projectName=FutList
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js
sonar.host.url=http://localhost:9000
sonar.token=sqp_3820cf92f73f844f26af60cd6e5c2d2b0dce589d

# Configuração de testes (caso tenha Jest/Vitest com coverage)
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info